project:
  type: website
  output-dir: docs

website:
  page-footer: "[#datiBeneComune](https://www.datibenecomune.it/)"
  navbar:
    search: false
    logo: "imgs/logo.png"
    background: primary
    left:
      - href: index.qmd
        text: Home
  twitter-card:
    card-style: "summary_large_image"
  open-graph:
    description: "A 44 anni dall'approvazione della legge sull'aborto, i dati sulla sua applicazione non sono aperti, correnti e riusabili"

format:
  html:
    lang: it
    theme: cosmo
    css: styles.css
    toc: false
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/www\.quarto\.org\/custom'
